language: generic
sudo: required

services:
  - docker

before_script:
  - chmod -R o+w .
  - env | grep TRAVIS > /tmp/travis.env
  - env | grep GITHUB >> /tmp/travis.env || true
  - env | grep S3 >> /tmp/travis.env || true
  - env | grep DISTRONAME >> /tmp/travis.env

  - |
    docker pull blizzlike/buildenv:${DISTRONAME}
    docker run \
      --name buildenv-${DISTRONAME} -d \
      -v $(pwd):/home/blizzlike/development \
      -v /tmp/release:/home/blizzlike/release \
      --env-file /tmp/travis.env \
      blizzlike/buildenv:${DISTRONAME} tail -f /dev/null

stages:
  - build
  - publish

jobs:
  include:
    # build binary packages
    - stage: build
      env:
        - DISTRONAME=stretch
      script:
        - |
          docker exec -t buildenv-${DISTRONAME} \
            lua5.1 ./travis/core.lua

    # publish build results
    - stage: publish
      env:
        - DISTRONAME=stretch
      script:
        - |
          docker exec -t buildenv-${DISTRONAME} \
            lua5.1 ./travis/core.lua

notifications:
  webhooks:
    urls:
      - https://w2d.blizzlike.org/v1/travis
    on_start: always
